name: goreleaser

on:
  workflow_dispatch:
  pull_request:
  push:
    # run only against tags
    tags:
      - "*"
    branches:
      - main

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Clone Repository and run GoReleaser
        run: |
          git clone https://github.com/leetatech/goreleaser &&
          cd goreleaser &&
          go build -o ./cmd/gorelease . &&
          ./cmd/gorelease --owner leetatech --repo ${{ github.event.repository.name }} --token ${{ secrets.LEETA_GITHUB_TOKEN }} --email ${{ github.event.pusher.email }} --author ${{ github.event.pusher.name }} --version minor 

